UI-MVC/Models/CreateTicketViewModel.cs
namespace SC.UI.Web.MVC.Models;

public class CreateTicketViewModel
{
    public int AccId { get; set; }
    public string Problem { get; set; }
}

UI-MVC/Models/Dto/NewTicketResponseDTO.cs
namespace SC.UI.Web.MVC.Models.Dto;

public class NewTicketResponseDTO
{
    public int TicketNumber { get; set; }
    public string ResponseText { get; set; }
    public bool IsClientResponse { get; set; }
}

UI-MVC/Models/Dto/TicketResponseDTO.cs
namespace SC.UI.Web.MVC.Models.Dto;

public class TicketResponseDTO
{
    public int Id { get; set; }
    public string Text { get; set; }
    public DateTime Date { get; set; }
    public bool IsClientResponse { get; set; }
    public int TicketNumberOfTicket { get; set; }
}

UI-MVC/Models/ErrorViewModel.cs
namespace SC.UI.Web.MVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

UI-MVC/Controllers/Api/TicketResponsesController.cs
using Microsoft.AspNetCore.Mvc;
using SC.BL;
using SC.BL.Domain;
using SC.UI.Web.MVC.Models.Dto;

namespace SC.UI.Web.MVC.Controllers.Api;

[ApiController]
[Route("api/[controller]")]
public class TicketResponsesController : ControllerBase
{
    private readonly ITicketManager _mgr;

    public TicketResponsesController(ITicketManager ticketManager)
    {
        _mgr = ticketManager;
    }

    // GET: api/TicketResponses?ticketNumber=5
    [HttpGet]
    public IActionResult Get(int ticketNumber)
    {
        var responses = _mgr.GetTicketResponses(ticketNumber);

        if (responses == null || !responses.Any())
            return NoContent();

        List<TicketResponseDTO> responseDtos = new List<TicketResponseDTO>();
        foreach (var response in responses)
        {
            responseDtos.Add(new TicketResponseDTO()
            {
                Id = response.Id,
                Text = response.Text,
                Date = response.Date,
                IsClientResponse = response.IsClientResponse,
                TicketNumberOfTicket = response.Ticket.TicketNumber
            });
        }

        return Ok(responseDtos);
    }

    // POST: api/TicketResponses
    [HttpPost]
    public IActionResult Post(NewTicketResponseDTO response)
    {
        TicketResponse createdResponse =
            _mgr.AddTicketResponse(response.TicketNumber, response.ResponseText, response.IsClientResponse);

        if (createdResponse == null)
            return BadRequest("Er is iets misgelopen bij het registreren van het antwoord!");

        TicketResponseDTO responseDto = new TicketResponseDTO()
        {
            Id = createdResponse.Id,
            Text = createdResponse.Text,
            Date = createdResponse.Date,
            IsClientResponse = createdResponse.IsClientResponse,
            TicketNumberOfTicket = createdResponse.Ticket.TicketNumber
        };

        return CreatedAtAction("Get", new {id = responseDto.Id}, responseDto);
    }
}

UI-MVC/Controllers/Api/TicketsController.cs
using Microsoft.AspNetCore.Mvc;
using SC.BL;
using SC.BL.Domain;

namespace SC.UI.Web.MVC.Controllers.Api;

[ApiController]
[Route("api/[controller]")]
public class TicketsController : Controller
{
    private readonly ITicketManager _mgr;

    public TicketsController(ITicketManager ticketManager)
    {
        _mgr = ticketManager;
    }

    // PUT: api/Tickets/5/State/Closed
    [HttpPut("{id}/State/Closed")]
    public IActionResult PutTicketStateToClosed(int id)
    {
        Ticket ticket = _mgr.GetTicket(id);

        if (ticket == null)
            return NotFound();

        ticket.State = TicketState.Closed;
        _mgr.ChangeTicket(ticket);

        return NoContent();
    }
}

UI-MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SC.UI.Web.MVC.Models;

namespace SC.UI.Web.MVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }
}

UI-MVC/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using SC.BL;
using SC.BL.Domain;
using SC.UI.Web.MVC.Models;

namespace SC.UI.Web.MVC.Controllers;

public class TicketController : Controller
{
    private readonly ITicketManager _mgr;

    public TicketController(ITicketManager ticketManager)
    {
        _mgr = ticketManager;
    }
    
    // GET: /Ticket
    public IActionResult Index()
    {
        IEnumerable<Ticket> tickets = _mgr.GetTickets();
        return View(tickets);
    }
    
    // GET: /Ticket/Details/<ticket_number>
    public IActionResult Details(int id)
    {
        Ticket ticket = _mgr.GetTicket(id);
        
        if(ticket.Responses != null)
            ViewBag.Responses = ticket.Responses;
        else
            ViewBag.Responses = _mgr.GetTicketResponses(ticket.TicketNumber);
        
        return View(ticket);
    }
    
    // GET: /Ticket/Edit/<ticket_number>
    public IActionResult Edit(int id)
    {
        Ticket ticket = _mgr.GetTicket(id);
        return View(ticket);
    }

    // POST: /Ticket/Edit/<ticket_number>
    [HttpPost]
    public IActionResult Edit(int id, Ticket ticket)
    {
        /*
        _mgr.ChangeTicket(ticket);
        return View(ticket);
        */
        
        if(!ModelState.IsValid)
            return View(ticket);
            
        _mgr.ChangeTicket(ticket);
        return RedirectToAction("Details", new {id = ticket.TicketNumber});
    }
    
    // GET: /Ticket/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: /Ticket/Create
    [HttpPost]
    /*
    public IActionResult Create(int accId, string problem)
    {
        Ticket newTicket = _mgr.AddTicket(accId, problem);
        return RedirectToAction("Details", new {id = newTicket.TicketNumber});
    }
    */
    public IActionResult Create(CreateTicketViewModel createTicket)
    {
        Ticket newTicket = _mgr.AddTicket(createTicket.AccId, createTicket.Problem);
        return RedirectToAction("Details", new {id = newTicket.TicketNumber});
    }
    
    // GET: /Ticket/Delete/<ticket_number>
    public IActionResult Delete(int id)
    {
        Ticket ticket = _mgr.GetTicket(id);
        return View(ticket);
    }

    // POST: /Ticket/Delete/<ticket_number>
    [HttpPost]
    public IActionResult DeleteConfirmed(int id)
    {
        _mgr.RemoveTicket(id);
        return RedirectToAction("Index");
    }
}

UI-MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Welkom";
}

<div class="my-4 p-5 bg-light rounded">
    <h1>SupportCenter</h1>
    <p>Welkom op het online helpdesk systeem.</p>
</div>

<div class="row">
    <div class="col col-md-4">
        <h2>Nieuw ticket</h2>
        <p>Maak een nieuw ticket aan in het systeem.</p>
        <a class="btn btn-light" role="button" asp-controller="Ticket" asp-action="Create">Nieuw ticket</a>
    </div>
    <div class="col col-md-4">
        <h2>Alle tickets</h2>
        <p>Toont een lijst van alle bestaande tickets.</p>
        <a class="btn btn-light" role="button" asp-controller="Ticket" asp-action="Index">Alle tickets</a>
    </div>
    <div class="col col-md-4">
        <h2>Toon ticket</h2>
        <p>Geeft de details van één ticket.</p>
        @*<a class="btn btn-light" role="button" href="#">Toon ticket</a>*@
        <form asp-controller="Ticket" asp-action="Details" method="get" class="row row-cols-auto">
            <input name="id" type="number" placeholder="Ticketnummer"/>
            <input type="submit" value="Toon ticket" class="btn btn-light"/>
        </form>
    </div>
</div>

UI-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - SupportCenter</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/UI_MVC.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SupportCenter</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; SupportCenter
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UI-MVC/Views/Ticket/Create.cshtml
@model SC.UI.Web.MVC.Models.CreateTicketViewModel

@{
    ViewBag.Title = "Ticket aanmaken";
}

<h2>Ticket aanmaken</h2>

<form asp-controller="Ticket" asp-action="Create" method="post">
    <div class="form-group">
        @*
        <label for="accId">Account-id</label>
        <input id="accId" name="accId" type="number" class="form-control"/>
        *@
        <label asp-for="AccId">Account-id</label>
        <input asp-for="AccId" class="form-control"/>
    </div>
    <div class="form-group">
        @*
        <label for="problem">Probleem</label>
        <input id="problem" name="problem" type="text" class="form-control"/>
        *@
        <label asp-for="Problem">Probleem</label>
        <input asp-for="Problem" class="form-control"/>
    </div>
    <input type="submit" value="Verzenden"/>
</form>

UI-MVC/Views/Ticket/Delete.cshtml
@model SC.BL.Domain.Ticket

@{
    ViewBag.Title = "Ticket verwijderen";
}

<h2>Ticket verwijderen</h2>
<p>Ben je zeker dat je onderstaand ticket (ID: @Model.TicketNumber) wenst te verwijderen?</p>

@*<dl class="dl-horizontal">
    <dt>Account</dt><dd>@Model.AccountId</dd>
    <dt>Probleem</dt><dd>@Model.Text</dd>
    <dt>Aangemaakt op</dt><dd>@Model.DateOpened</dd>
    <dt>Status</dt><dd>@Model.State</dd>
</dl>*@
<partial name="_TicketDetailsPartial" for="@Model"/>

<form asp-controller="Ticket" asp-action="DeleteConfirmed" asp-route-id="@Model.TicketNumber" method="post">
    <input type="submit" value="Verwijderen"/> | <a asp-action="Index">Annuleer</a>
</form>

UI-MVC/Views/Ticket/Details.cshtml
@using SC.BL.Domain
@model SC.BL.Domain.Ticket

@{
    ViewBag.Title = "Ticket";
}

<h2>Ticket (ID: <span id="ticketNumber">@Model.TicketNumber</span>)</h2>

@*<dl>
    <dt>Account</dt><dd>@Model.AccountId</dd>
    <dt>Probleem</dt><dd>@Model.Text</dd>
    <dt>Aangemaakt op</dt><dd>@Model.DateOpened</dd>
    <dt>Status</dt><dd>@Model.State</dd>
</dl>*@
<partial name="_TicketDetailsPartial" for="@Model"/>

<a asp-action="Edit" asp-route-id="@Model.TicketNumber">Bewerk</a>
 | <a asp-action="Index">Lijst</a>

<h3 class="mt-3">Responses</h3>
<p><button id="loadResponses">(Her)laad antwoorden</button></p>
<table id="responses" class="table">
    <thead>
        <tr>
            <th>Antwoord</th><th>Datum</th><th>Klant antwoord?</th>
        </tr>
    </thead>
    <tbody>
        @foreach (TicketResponse response in (IEnumerable<TicketResponse>) ViewBag.Responses)
        {
            <tr>
                <td>@response.Text</td>
                <td>@response.Date</td>
                <td><input asp-for="@response.IsClientResponse" disabled/></td>
            </tr>
        }
    </tbody>
</table>
<input id="responseText" type="text" style="margin-right: 5px" />
<button id="createResponse">Verzenden</button>

@section Scripts {
    <script src="~/js/ticket/details.js" defer></script>
}

UI-MVC/Views/Ticket/Edit.cshtml
@model SC.BL.Domain.Ticket

@{
    ViewBag.Title = "Ticket wijzigen";
}

<h2>Ticket wijzigen</h2>

<form asp-controller="Ticket" asp-action="Edit" asp-route-id="@Model.TicketNumber" method="post">
    <div class="form-group">
        <label asp-for="TicketNumber">Id</label><input asp-for="TicketNumber" class="form-control" readonly/>
        <span asp-validation-for="TicketNumber" class="text-danger"></span>
    </div>
    @*
    <!-- or -->
    <input asp-for="TicketNumber" type="hidden"/>
    *@
    
    <div class="form-group">
        <label asp-for="AccountId">Account</label><input asp-for="AccountId" class="form-control"/>
        <span asp-validation-for="AccountId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Text">Probleem</label><input asp-for="Text" class="form-control"/>
        <span asp-validation-for="Text" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="DateOpened">Aangemaakt op</label><input asp-for="DateOpened" class="form-control"/>
        <span asp-validation-for="DateOpened" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="State">Status</label>@*<input asp-for="State" class="form-control"/>*@
        <select asp-for="State" asp-items="@(new SelectList(Enum.GetValues<SC.BL.Domain.TicketState>()))" class="form-select"></select>
        <span asp-validation-for="State" class="text-danger"></span>
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="submit" value="Opslaan"/> | <a asp-action="Index">Annuleer</a>
</form>

UI-MVC/Views/Ticket/Index.cshtml
@model System.Collections.Generic.IEnumerable<SC.BL.Domain.Ticket>

@{
    ViewBag.Title = "Tickets";
    /*Layout = "_Layout";*/ // standaard indegsteld in '_ViewStart.cshtml'
}

<h2>Tickets</h2>
 <p><a asp-action="Create">Nieuw ticket</a></p> 
<table class="table">
    <tr>
        <th>Nummer</th>
        <th>Account</th>
        <th>Probleem</th>
        <th>Aangemaakt op</th>
        <th>Status</th>
        <th></th>
    </tr>
    @foreach (SC.BL.Domain.Ticket ticket in Model)
    {
        <tr>
            <td>@ticket.TicketNumber</td>
            <td>@ticket.AccountId</td>
            <td>@ticket.Text</td>
            <td>@ticket.DateOpened</td>
            <td>@ticket.State</td>
            <td>
                <a asp-action="Details" asp-route-id="@ticket.TicketNumber">Details</a>
                 | <a asp-action="Edit" asp-route-id="@ticket.TicketNumber">Bewerk</a>
                 | <a asp-action="Delete" asp-route-id="@ticket.TicketNumber">Verwijder</a>
            </td>
        </tr>
    }
</table>

UI-MVC/Views/Ticket/_TicketDetailsPartial.cshtml
@model SC.BL.Domain.Ticket

<dl>
    <dt>Account</dt><dd>@Model.AccountId</dd>
    <dt>Probleem</dt><dd>@Model.Text</dd>
    <dt>Aangemaakt op</dt><dd>@Model.DateOpened</dd>
    <dt>Status</dt>
    <dd>
        <span id="state">@Model.State</span>
        @if (Model.State != SC.BL.Domain.TicketState.Closed)
        {
          <button id="changeStatusToClosed">Close</button>
        }
    </dd>
</dl>